### ISSUE TITLE
can i change the target.bin

### ISSUE THREAD

**Issue by hillday** [makehuman-js/makehuman-js#1]
Hi,i very like this project!can i get more detail docs,such as api docs.others,i found the target.bin is large too  ,i hope to use it in mobile project and need smaller target.bin.
what should I do?

**Comment by wassname** [comment]
Thanks. It's a new project so your feedback is usefull. Could you let me know what documents would be useful, and maybe rank them?

I agree it is big (at 250mb). Do you mean that it's too big for downloading, packaging into an app, or for memory? There are a couple of options:
- gzip compression like I did with http://mhwebui.wassname.com/. You only download 19.3Mb, then it's unpacked into 250mb and loaded into memory. 
- Use less modifiers. This hasn't been implemented yet, but would only be a couple of days work. In the scenario you would have less sliders available.

**Comment by hillday** [comment]
@wassname Thanks.
1. If has a documents to description like Human、Modifier、Targets object and they relations,more than i can find every api is do what?how to use it and many more.I think they will help me more fast to use this project.
2.With it is big, i hope use less modifiers,if can customize modifiers which helpful to me,
it was lucky for me.

**Comment by wassname** [comment]
Since I have limited time, do you have any ideas for what kind of documentation would be most helpful for now, perhaps a commented example? 

Perhaps you have already seen these but right now I have descriptions in the comments [some objects](https://github.com/makehuman-js/makehuman-js/blob/master/src/js/human/human.js#L363), but it's not complete. There is also the [example](https://github.com/makehuman-js/makehuman-js-example/blob/master/js/main.js#L101) helpful? 

It sounds like you would like the option to customize which modifiers you use. That's good to know, I can't say when I'll get time to do it because I'm busy working two jobs, but it's on my todo list.

**Comment by hillday** [comment]
Thanks,a commented example is more helpful for me.Year,I have already seen the example which is help me fast to learn project.

If it is possible,the way to make modifier less can share me?And I can do it myself.

**Comment by wassname** [comment]
Good to know thanks.

It might be hard for you to do sorry since I haven't documented the generation of targets.bin well. I need to go to https://github.com/makehuman-js/makehuman-data and use the `scripts/notebooks/Export_targets_to_bin.ipynb` to make alternate bin files. Then I need to make matching `src/json/modifiers/modeling_modifiers.json`, and publish the new version (or you could modify the version in your node modules folder). Then finally I have to change makehuman.js to handle different amounts of modifiers (a quick way is to comment [this](https://github.com/makehuman-js/makehuman-js/blob/master/src/js/human/human-modifier.js#L107) out).

I might not find time for a couple of weeks sorry, but I do plan to do it.

**Comment by hillday** [comment]
Thank you very much.I have read project source code,and try to coding a tool to generation target.bin.When I use generation data to replace old data,I get a problem with target-list.json is not replace success,for debug I try to rename target-list.json to target-list.json.bak,then found the variable targetList value also is full target list,how can i change target-list.json? 
This is my tool source code https://github.com/hillday/makehuman-target-generator

**Comment by wassname** [comment]
Nice work! Could you give me the full error and context? I'm not sure if these errors are in makehuman-js, and what file and function.

You shouldn't need to change targets-list.json, as it's hardcoded target metadata. You can load a subset of the targets but still have the full metdata and it should be fine. It's used here https://github.com/makehuman-js/makehuman-js/blob/f9225f7cf4df989b47e4d98a53900520cca76597/src/js/human/targets.js.

**Comment by hillday** [comment]
Yeah,I found targets-list.json is hardcoded in targets.js. I replace the meta file and rebuild it,and it worked,but found 'targets.js:305 Assertion failed: console.assert' error when application running,with source code in targets.js 'console.assert(_.sum(this.targetData.slice(3 * m, 4 * m)) === 2952)'.

**Comment by wassname** [comment]
Nice. Ah you can remove that, I was just checking the full amount of targets loaded. Not relevant anymore.

**Comment by hillday** [comment]
Now,I success replace target.bin and run right,but modifier exception.I generation a target.bin only with modifier 'nose-scale-depth',when I modifier gui,It is actually modifier armslegs other then nose.If the target-list.json order is mapping target.bin index,like 'data/targets/expression/units/african/nose-compression.target' in target-list.json is index 0 and  mapping to target.bin index from 0 to 19158 * 3?

**Comment by wassname** [comment]
Sounds like your almost there, good stuff. I'm not 100% sure what your asking in that last sentence but it sounds like you understand it correctly. Like in the [comment in targets.js](https://github.com/makehuman-js/makehuman-js/blob/master/src/js/human/targets.js#L292), and like you said, the first target in targets-list.json corresponds to 0 to 19158 * 3th numbers in targets.bin.

**Comment by hillday** [comment]
Thank you very much.The problem is solved.I'm sorry to have wasted your time,Thanks again!

**Comment by wassname** [comment]
Great! You haven't, it's just cool that someones using something I made :) 

If you feel like making any pull request's, they'll be welcome.
