### ISSUE TITLE
Android Compatibility

### ISSUE THREAD

**Issue by hernanpatronc** [makehuman-js/makehuman-js#11]
Hi!
I've been trying to run the example project but in android it fails giving the following warning: 
"WebGLRenderer: too many bones - 326, this GPU supports just 251 (try OpenGL instead of ANGLE)"
And then these two errors:
"THREE.WebGLShader: Shader couldn't compile."
 "THREE.WebGLShader: gl.getShaderInfoLog() vertex ERROR: too many uniforms"

Can anybody help me?

**Comment by wassname** [comment]
That's interesting, I didn't know mobile gpus might have different limits. This would likely be an issue with many THREE.js demos on the same phone. What gpu is on that phone (or which phone is it)?

One possible fix, but it would take a lot of fiddling, would be to regenerate the source data using a simpler skeleton. For that you would need to run the scripts for this repo https://github.com/makehuman-js/makehuman-data . It's not that well documented since not many people have used it, but you need to know some python, and look at the closed issues which describe some similar efforts (to add IO, and add new poses).
