### ISSUE TITLE
export human to .obj file 

### ISSUE THREAD

**Issue by hillday** [makehuman-js/makehuman-js#2]
I meet a new problem which I try to export base human to a .obj file, and I open .obj file to 3D view software find  the model has hair 、clothes.But the base human is no hair,no clothes in web application,why is that?

**Comment by wassname** [comment]
So when you look at it 3D Software it has the hair helpers. This is something I recently fixed so you might not be using the latest version.  

Perhaps you could try looking at your human.js and minde. Go in node_modules/makehuman/src/human.js and comparing it [the latest code](https://github.com/makehuman-js/makehuman-js/blob/0efa832d6255341172a446450f7a14482267e684/src/js/human/human.js#L85) .

**Comment by hillday** [comment]
That's ok.Thanks.

**Comment by hillday** [comment]
// delete unused, uvs, faces, and vertices
   geom.faceVertexUvs = geom.faceVertexUvs.filter((uv, i) => geom.faces[i].materialIndex === 0)
This statement maybe has a bug,the 'geom.faceVertexUvs[0] = geom.faceVertexUvs[0].filter((uv, i) => geom.faces[i].materialIndex === 0)' is really right？

**Comment by wassname** [comment]
Yup, I'll explain what it's for. So I used face.materialIndex to assign each face to a group. Group one is the normal body, group 1+ are hidden helpers which we attach the clothes to. For example the hair helper looks like a helmet in the shape of a mullet. So this filters out faces that are not in group one, leaving us with only the body faces.

I added a download button to the example repo, so that might help you work out what's differen't.

Here's a workflow that works for me: If I
-  go to http://makehuman-js-example.wassname.com/ 
- hard reload by pressing Cntrl-F5 (I updated it today)
- type in the js console `copy(app.human.io.toObj())`  (this copys to clip board in chrome)
- then paste it into `human.obj` 
- then import human.obj into blender.
- observe that It shows up in blender as just the body, with no helpers visible.

Can you try those steps on the example website and see if it works for you? If it does you can compare the code in makehuman-js-example.wassname.com to your deployment, and that will let you narrow down your problem.

**Comment by hillday** [comment]
Thanks,I try to store `app.human.io.toObj() ` return value to a Blob object and download it to a file which is show in blender only body,with no helper visible.
Thanks again!

**Comment by wassname** [comment]
That's what you wanted I think. If so I'm glad it worked!
