### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by snoblenet** [makehuman-js/makehuman-js#3]
Hi Mike,

Is there documentation for these repos anywhere?

Both how to use them, but also basic concepts like how your code is speaking to the MakeHuman binary.

Cheers,

Steven

**Comment by wassname** [comment]
No not yet sorry (due to lack of time). What I do have is an [commented example](https://github.com/makehuman-js/makehuman-js-example/blob/master/js/main.js#L101). And [comment in the makehuman code](https://github.com/makehuman-js/makehuman-js/blob/master/src/js/human/targets.js#L292).

I'll add more documentation when I have time (two part time jobs at the moment). If you feel like improving the comments feel free to make them into PR's, they would be welcome.

**Comment by snoblenet** [comment]
Thanks I'll review the comments.
